### ISSUE TITLE
Broken Playground, Flem.io, and site example

### ISSUE THREAD

**Issue by bryhasagithub** [erikvullings/mithril-markdown#1]
I was successful with the basic step instructions but wanted to let you know that the playground links and the repo example github link don't work.

The [playground link](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4IWAA60ATsQAEcrHLDTaSgORYIxQtOgABNDAAexdQG4AOmnFTZc4HICyGaQGsAJrQDuaAKIe2jJyrMqqGlo6elAAtFiunj5oFtbWQnDyJtgSsHIAvHIAFACU+QB8DtYK6fIZGIz5lWgKCvHuXr6IcgAG1gDEcgDChBgSjNKpaH0DAMow1MQQ9JMAVCuDADIAkoMA0nIA8gByzn5yACoHcjPnAIIASudyfgAiW+dbRwDia5MAahA4No5MgvrRaABzWAAXUKJGIEjgiAA9MjvOj8BDwVCYPg6FhivhJudCIC5GSMHI4IQZPIoBAjES0NYjj45DoyRS5AA3GDSACecig9AhQoZMAo5OEaA8MA87Nocm80lGUvZhBgcjlQWk+DkACEAK7ybzaGnGsVGABG0hgGDccElcEV3g1zW8mokfLAMiUlKwhqgi3pRjkGAWSzQkuB1NogflVs1xFt9TlYbgYapDJxltxxNJGa5sfs9IyTL84cIufJGbgMAkrlTCcFlJDMBtdrcTKcgeD4rDEfotfNUATnu9vrT9C1ldzTN6zRCVTktuIhukzWAy4U3IgMG8XRK5SaLRaNQcigSHWaoQKdUYVkXp9X6+aWEKLnaSQCOsljjaiS+CExTbiEFDLqw1iQcyaBYPgWBxgwhReNQho4Aw+BWrQHj8pKWSSLAxSUCAdawIOaAIDwACMAAciAAExUWwHAgJgOB4HicACDQ9CMMwPD4HoEIkCeyjCvUXRCSJACEti0hgDCPtBjCmK4dqiaaHg6F0VEAAy6QApI+ChWuGbgQqohoyjEdDCtIXTJgpcANrailQcRpHzIsQ54AALIgVG+Ww0KsEAA) doesn't work and results in this error (screenshot below):
![Screen Shot 2019-10-18 at 11 28 52 AM](https://user-images.githubusercontent.com/11837954/67118837-a5c63a00-f19a-11e9-9699-1b6fec1b18e2.png)

The site example link takes me to a 404:
reproduction steps:

- https://erikvullings.github.io/mithril-markdown/#!/home
- click on "example"
- redirects me to here: https://erikvullings.github.io/markdown-editor 
- Screenshot below
![Screen Shot 2019-10-18 at 11 29 04 AM](https://user-images.githubusercontent.com/11837954/67118864-b4145600-f19a-11e9-8fec-8defd8c533cc.png)

**Comment by erikvullings** [comment]
@bryhasagithub Thanks for the feedback (and sorry for the delay in answering). I've released a new version which fixes both issues.
